//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lava.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LavaEntities : DbContext
    {
        public LavaEntities()
            : base("name=LavaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LAVA_BLOB_TRIGGERS> LAVA_BLOB_TRIGGERS { get; set; }
        public virtual DbSet<LAVA_CALENDARS> LAVA_CALENDARS { get; set; }
        public virtual DbSet<LAVA_CRON_TRIGGERS> LAVA_CRON_TRIGGERS { get; set; }
        public virtual DbSet<LAVA_FIRED_TRIGGERS> LAVA_FIRED_TRIGGERS { get; set; }
        public virtual DbSet<LAVA_JOB_DETAILS> LAVA_JOB_DETAILS { get; set; }
        public virtual DbSet<LAVA_LOCKS> LAVA_LOCKS { get; set; }
        public virtual DbSet<LAVA_PAUSED_TRIGGER_GRPS> LAVA_PAUSED_TRIGGER_GRPS { get; set; }
        public virtual DbSet<LAVA_SCHEDULER_STATE> LAVA_SCHEDULER_STATE { get; set; }
        public virtual DbSet<LAVA_SIMPLE_TRIGGERS> LAVA_SIMPLE_TRIGGERS { get; set; }
        public virtual DbSet<LAVA_SIMPROP_TRIGGERS> LAVA_SIMPROP_TRIGGERS { get; set; }
        public virtual DbSet<LAVA_TRIGGERS> LAVA_TRIGGERS { get; set; }
        public virtual DbSet<LAVA_USER> LAVA_USER { get; set; }
    }
}
